version: '3'
services:
  postgres_NEW2:
    image: postgres:12
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres


      